### ISSUE TITLE
Question: Suggestions for reading?

### ISSUE THREAD

**Issue by mateicanavra** [Semantic-Web-Working-Ontologist/KGCBookClub#26]
Are there any suggestions for how to approach reading the book (additional resources, etc.), especially for those new to the Semantic Web?

**Comment by mateicanavra** [comment]
- Run all of the examples on Data.World (https://data.world/)
- Work together on Slack channel on queries & examples

**Comment by dallemang** [comment]
We're assembling a [Bibliography](../wiki/References) in response to specific questions from the meetings.
