### ISSUE TITLE
Using Protege to run Ch 6 Queries 

### ISSUE THREAD

**Issue by ghost** [Semantic-Web-Working-Ontologist/KGCBookClub#46]
I down loaded family.ttl and imported into Protege 
[Family.txt](https://github.com/Semantic-Web-Working-Ontologist/KGCBookClub/files/5343336/Family.txt)

I copy the 6.28 Query into Protege SPARQL 
[Protege-Familyttl-Ch6-28Query.pdf](https://github.com/Semantic-Web-Working-Ontologist/KGCBookClub/files/5343389/Protege-Familyttl-Ch6-28Query.pdf)

I get the following results
[CH6Q6-28-Results.pdf](https://github.com/Semantic-Web-Working-Ontologist/KGCBookClub/files/5343364/CH6Q6-28-Results.pdf)

The queries 6.1 to 6.26 run in Protege the same as data world 

Am I doing something wrong.

**Comment by dallemang** [comment]
You added in the prefix declaration for family: (data.world does this for you, but for Protege, you need to be explicit), which was correct. 

however, you added a period (".") at the end of that declaration, just as the error message says; it found a "." at line 4 column 77.  No period appears at the end of prefix declarations in SPARQL.  I'm sure if you remove that . your query will work. 

Just an aside comment; I think it was very sloppy of the committees to make SPARQL look like turtle, except when it comes to prefixes; prefix declarations in turtle use "@" and ".", whereas in SPARQL they do not.     I have been using both of these languages for years now, and I still don't remember this, and have to look it up every time (I had to look it up for this answer).   This is a nuisance as well if you are trying to manage namespace in your system; I often maintain a namespace manager in applications I build.  I construct a file of all known namespaces.  I have to maintain it in two different formats, and append it when needed. This is such a silly thing to have to do.

**Comment by ghost** [comment]
Thanks
    On Monday, October 12, 2020, 10:20:48 AM EDT, Dean Allemang <notifications@github.com> wrote:  
 
 


You added in the prefix declaration for family: (data.world does this for you, but for Protege, you need to be explicit), which was correct.

however, you added a period (".") at the end of that declaration, just as the error message says; it found a "." at line 4 column 77. No period appears at the end of prefix declarations in SPARQL. I'm sure if you remove that . your query will work.

Just an aside comment; I think it was very sloppy of the committees to make SPARQL look like turtle, except when it comes to prefixes; prefix declarations in turtle use "@" and ".", whereas in SPARQL they do not. I have been using both of these languages for years now, and I still don't remember this, and have to look it up every time (I had to look it up for this answer). This is a nuisance as well if you are trying to manage namespace in your system; I often maintain a namespace manager in applications I build. I construct a file of all known namespaces. I have to maintain it in two different formats, and append it when needed. This is such a silly thing to have to do.
