### ISSUE TITLE
Ch 6 38/39/40Queries

### ISSUE THREAD

**Issue by ghost** [Semantic-Web-Working-Ontologist/KGCBookClub#49]
When I use Protege for the queries I get blank results.
[QueriesCH6-38-39-40.pdf](https://github.com/Semantic-Web-Working-Ontologist/KGCBookClub/files/5374189/QueriesCH6-38-39-40.pdf)

When I open linkedMDB.ttl in Notebook++and search for foaf:page I get nothing.

Am I doing something wrong when I use Protege

**Comment by dallemang** [comment]
It looks as though something has gone wrong with the namespace prefixes in that file (I'll see if I can fix that).  The foaf references are done using the full URL, i.e., <http://xmlns.com/foaf/0.1/page>

If you search for that, you get all the links. 


As for Protege's answer; I'm not sure, it seems that you are doing the right thing.  But I do know that Protege's SPARQL facility is not fully up to the standard, but I don't know what it is missing. 


Try removing the filters (maybe Protege doesn't implement "in"?), but do a "LIMIT 10" at the end (so you don't overload your output)

**Comment by ghost** [comment]
Since I am not having  lot of success using Protege. Do you have a recommendation for a product that is better aligned to working with your examples.  
Thanks for taking time to provide feedback.
    On Wednesday, October 14, 2020, 10:27:33 AM EDT, Dean Allemang <notifications@github.com> wrote:  
 
 


It looks as though something has gone wrong with the namespace prefixes in that file (I'll see if I can fix that). The foaf references are done using the full URL, i.e., http://xmlns.com/foaf/0.1/page

If you search for that, you get all the links.

As for Protege's answer; I'm not sure, it seems that you are doing the right thing. But I do know that Protege's SPARQL facility is not fully up to the standard, but I don't know what it is missing.

Try removing the filters (maybe Protege doesn't implement "in"?), but do a "LIMIT 10" at the end (so you don't overload your output)
