### ISSUE TITLE
Homework (Scientific Theory Modelling )

### ISSUE THREAD

**Issue by TheodoraPetkova** [Semantic-Web-Working-Ontologist/KGCBookClub#52]
@dallemang et al. This is my homework. My attempt was to go basic - with only the first and the second task. My cognitive capacity for now won't allow me to understand the other relationships, i.e. temporal etc. I created a model in Protege and the owl file is here: https://drive.google.com/file/d/1BvWbOfBEBjumfP1hPNlsOBH8I65F70vj/view?usp=sharing  [edit] Also here in Github: https://github.com/TheodoraPetkova/KGCBookClub/blob/master/ThirdDraftSceintificModelTeodoraHomework.owl

Just for reference, I started with thinking about the classes and the entities, and then tried to create relationships between them with Protege. Which kind of limited what I first envisioned [see below] And last, I tried to create at least several individuals of the classes created - the Dialogic PR theory, M.L.Kent (scientist) and the Dialogue ()main concept of the theory)

Thanks for lookign at this and for the stimulating homework!

Theory [What is the generalia [supreme genus] of Theory, like Place←----> city ←----->country, maybe Complex Construct/Episteme]

Hypothesis
Model
Framework
Principle
Concept
Definition
Term
Fact 
Axiom
Theorem
Author

Properties
hasAuthor
hasIntendedScope (Investigates)
UsedToInterpret
HasScientificDomain
HasScientificDiscipline

hasNonFormalAspects
mentionsAuthor
mentionsDatasets
mentionsObservations
hasObjections
isDevelopedBasedOn
isDefinedBy

**Comment by dallemang** [comment]
Thanks for providing this - we discussed it in the meeting; closing the issue just to clean out the issue list.
