### ISSUE TITLE
Question on Chapter 09: extending modeling languages

### ISSUE THREAD

**Issue by mateicanavra** [Semantic-Web-Working-Ontologist/KGCBookClub#53]
When does it make sense to actually extend RDFS or OWL? Should that only be reserved for standards organizations?

**Comment by dallemang** [comment]
Anyone can say Anything about Any topic; that means that you can extend RDFS and OWL (or SKOS, for that matter).  But of course, your comments are yours, not the W3C's.   And for instance, nobody will get your extensions when they follow their nose to learn about, e.g., owl:equivalantClass .
