### ISSUE TITLE
Ch 10 pg 278 - 280 Schema.org semantics

### ISSUE THREAD

**Issue by ghost** [Semantic-Web-Working-Ontologist/KGCBookClub#55]
I am having a problem understanding how use of RDFS Range defers from schema: rangeIncludes. I am guessing that use of rdfs:range works across multiple ontology domains where schema:rangeIcludes works within a single ontology domain.  

Second unrelated question:  We have discussed using Construct to build triples through inference which facilitates identifying relationships that have not been stated explicitly.  How do someone then extract the related data they are looking?

Does someone run a Select query at the end of the Construct statement.  I think my question has to do with data persistence and my relational db experience and inexperience with semantic data capability.

**Comment by jtyzzer** [comment]
To your second question, unfortunately, while you can have SELECTs within CONSTRUCTs you can't do it the other way around. On my project, when we use CONSTRUCTs in the manner described the CONSTRUCT is either the end goal (i.e., we wanted a query with a graph result), or we use such a CONSTRUCT to prototype a subsequent INSERT statement to implement forward-chaining (where inferences are persisted in the triplestore, as opposed to backward-chaning, where inferences are made at query time by the reasoner). This is just what I've learned over the past year or so--like you, I come from a relational background. I'm re-tooling for my second act ;-).

**Comment by dallemang** [comment]
We seem to have lost your schema:rangeIncludes question.    As we have seen in the book. multiple ranges interact in a surprising way: 

p rdfs:range  C .
p rdfs:range D .

imples that 

p rdfs:range C INTERSECT D .


This is pretty odd; in most modeling, you want to be able to expand the range (respectively domain) of a property.   Hence, schema introduced its own notion of range that behaves this way.  The name rangeIncludes  was chosen to indicate that. 


p schema:rangeIncludes D . 
p schema:rangeIncludes C .

implies

p schema:rangeIncludes C UNION D .


The problem with this approach has to do with the open world assumption.  For example:

p rdfs:range  C .
s p x .

you can infer that 

x a C

This continues to be true, even if someone tells you more things about p, e.g., if they tell you that

p rdfs:range D . 

you don't have to re-evaluate what you inferred about x.


Contrast to schema:rangeIncludes

p schema:rangeIncludes C .
s p x 


Can you infer that 

x a C   

?

No, you can't; after all, someone might later on tell you that

p schema:rangeIncludes D .

and in fact, all along, x was a member of D, but not C. 

x a D .

This is why rdfs:range is the way it is; it needs to operate in the open world of a distributed system.
