### ISSUE TITLE
Ch. 11 question on OWL to SKOS conversion

### ISSUE THREAD

**Issue by ghost** [Semantic-Web-Working-Ontologist/KGCBookClub#57]
On page 316 there is reference of converting FIBO from OWL to SKOS. This seems really interesting. What motivates such a conversion? What's gained and what's lost in terms of the semantics? And is there any risk of getting the semantics wrong in the SKOS version if certain things (e.g. class expressions, owl restrictions, etc.) are unavailable?

**Comment by dallemang** [comment]
SKOS is more accessible in many situations than OWL, so FIBO publishes in both formats.  SKOS is less expressive than OWL, so some information is lost in this conversions.  That's why FIBO's expression in OWL is normative, while the expression in SKOS is not.
