### ISSUE TITLE
subClassOf vs equivalentClass

### ISSUE THREAD

**Issue by lrumanes** [Semantic-Web-Working-Ontologist/KGCBookClub#58]
On page 338,  why is Vegetarian defined using subClassOf instead of equivalentClass?  Does this imply there are entities who only eat vegetarian food who aren't vegetarians?

**Comment by dallemang** [comment]
That part of the model is just saying that IF someone is a vegetarian, THEN the thing they eat is vegetarian food.  You could say the other way around, and it would probably be true, but not needed for this example.
