### ISSUE TITLE
Chap 12 question

### ISSUE THREAD

**Issue by ghost** [Semantic-Web-Working-Ontologist/KGCBookClub#60]
I see examples in the chapter where the owl:Restriction is used either with rdfs:subClassOf (Vegetarian example on pg. 338) or with owl:equivalentClass (HighPriorityItem on pg. 335). They seem to do the same thing: populate a class with instances that meet the criteria of the restriction. Is that right? If so, in what circumstances would you use the owl restriction construct as a subclass and when would you use it with an equivalent class? Thanks!
--Nick Houlahan

**Comment by dallemang** [comment]
This depends on which way you want to draw conclusions;  X subclassOf [ a Restriction ...] says that IF you know something is a X, THEN you know it satisfies the restriction.   X equivalentClass [a Restriction ...] also says that IF you know something satisfies the restriction, THEN it is a member of X.   The "say what you mean, mean what you say" principle holds here; these are two different statements.  Which one do you want to express?
